services:
  cfddns:
    image: dingdangdog/cfddns:whoiam_0.1.4
    container_name: whoiam
    restart: always
    # network_mode: "host"
    volumes:
      - ./config.json:/app/config.json
    ports:
      - 12320:12320
