services:
  whoiam:
    image: dingdangdog/cfddns:whoiam_0.1.2
    container_name: whoiam
    restart: always
#    network_mode: "host"
    ports:
      - 12321:12321
    volumes:
      - ./config.json:/app/config.json